num = int(input('Digite um número:'))
print('O número digitado foi {}.'.format(num))
print('O dobro de {} é {}.'.format(num, (num*2)))
print('O triplo de {} é {}.'.format(num, (num*3)))
print('A raiz quadrada de {} é {}.'.format(num, (num**(1/2))))