frase = ('Curso em Vídeo Python 3')
print(frase)
print('Quantas vezes aparece a letra o?', frase.count('o'))
print('Quantas vezes aparece a letra O?', frase.count('O'))
print('Transformando em maiúsculas:', frase.upper())
print('Quantas vezes aparece a letra O?', frase.upper().count('O'))
print('Qual o comprimento da string tirando os espaços em excesso?', len(frase.strip()))
print('Replace:', frase.replace('Python 3','Android'))
print('Curso'in frase)
print(frase.find('Vídeo'))
print('Junior'in frase)
print(frase.find('Junior'))